export const GlobalVariable = Object.freeze({
    BASE_API_URL : "http://localhost:9003",
    MSJ_ERROR: "bg-danger",
    MSJ_OK: "bg-success",
    MSJ_INFO: "bg-info",
    MSJ_WRN: "bg-warning",
    CATEGORIES: [
        {"name": "Seleccione","value":""},
        {"name": "Artes marciales","value":"Artes marciales"},
        {"name": "Body and Mind","value":"Body and Mind"},
        {"name": "Cardio y ritmos","value":"Cardio y ritmos"},
        {"name": "Cyclingtech","value":"Cyclingtech"},
        {"name": "Fuerza y tono","value":"Fuerza y tono"},
        {"name": "Hiit","value":"Hiit"},
        {"name": "Movement","value":"Movement"},
        {"name": "Crossfit","value":"Crossfit"},
        {"name": "Yoga o Pilates","value":"Yoga o Pilates" },
        {"name": "Functional","value":"Functional"},
        {"name": "Deportes","value":"Deportes"},
        {"name": "Aqua","value":"Aqua"},
        {"name": "Aerobicos","value":"Aerobicos"},
        {"name": "Ballet","value":"Ballet"},
        {"name": "Boxeo","value":"Boxeo"},
        {"name": "Ciclismo","value":"Ciclismo"},
        {"name": "Combat","value":"Combat"},
        {"name": "Danza","value":"Danza"},
        {"name": "Defensa Personal","value":"Defensa Personal"},
        {"name": "Gimnasia","value":"Gimnasia"},
        {"name": "Futbol","value":"Futbol"},
        {"name": "Natacion","value":"Natacion"},  
        {"name": "Patinaje","value":"Patinaje"},
        {"name": "Rumba","value":"Rumba"},
        {"name": "Spining","value":"Spining"},
        {"name": "TRX","value":"TRX"},
        {"name": "Zumba","value":"Zumba"},
        {"name": "Otros","value":"Otros"}                                                                                         
    ]
})